server:
  port: 8080

spring:
  mvc:
    cors:
      mappings:
        /api/**:
          allowed-origins: "http://localhost:5173"
          allowed-methods: GET,POST,PUT,DELETE,OPTIONS
          allowed-headers: "*"
          allow-credentials: false